name: Check & fix styling

on: [push]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@2.4
        with:
          verboseMode: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: PHP Linting (Pint)"
