name: run-tests

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

    push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [^10.48.23, ^11.31]
        dependency-version: [prefer-lowest, prefer-stable]
        testbench: [^8.0, ^9.0]
        exclude:
            -   laravel: ^10.48.23
                php: 8.4
            -   laravel: ^10.48.23
                testbench: ^9.0
            -   laravel: ^11.31
                testbench: ^8.0

    name: PHP${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
